### ISSUE TITLE
statistic

### ISSUE THREAD

**Issue by fejp** [ac1235/core#5]
Bei mir kommt jedes mal, wenn ich versuche mir eine Statistic ausgeben zu lassen eine Fehlermeldung:

python src/statistic.py ai_templates/caveman.py ai_templates/crazy.py 10 -logTraceback (most recent call last):
  File "src/statistic.py", line 1, in <module>
    import gamelib_cs
  File "/home/meinRechner/Schreibtisch/Battle of AIs/core/src/gamelib_cs.py", line 55
SyntaxError: Non-ASCII character '\xc3' in file /home/meinRechner/Schreibtisch/Battle of AIs/core/src/gamelib_cs.py on line 55, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

Der Befehl ist genau der selbe wie im Beispiel, daran kann es also wohl nicht liegen

**Comment by fejp** [comment]
Hab die Lösung:
Man muss in Linux python 3 anstatt python benutzen. eventuell sollte man das auf der Hauptseite ergänzen
